
/* CREATION DE L'UTILISATEUR */ 
CREATE USER IF NOT EXISTS 'redacteur'@'localhost' IDENTIFIED BY PASSWORD '*07132B025FC737F08E1FAC2FC6C6E351DA82D3EC';GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'redacteur'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

/* CREATION DE LA DATA BASE */
CREATE DATABASE IF NOT EXISTS helb
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

-- CREATION DE LA TABLE users
CREATE TABLE IF NOT EXISTS `users` (
  `users_login` varchar(256) NOT NULL,
  `users_password` varchar(256) NOT NULL,
  PRIMARY KEY (`users_login`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `users` (`users_login` , `users_password`) VALUES
('ADMIN@HELB.com', 'ADMIN')
